

```{r}
rm(list=ls(all=TRUE)) #clear data
library(dplyr)
library(ggplot2)
library(readxl)
library(gridExtra)
library(Hmisc)
library(MASS)
```

```{r}
data <- read_xlsx("Heineken.xlsx")
names(data)
head(data,5)
```

```{r}
## dependent variables
sales <-data$Volume_Sales_1000Liter
aware <- data$Awareness_Pct

## independent variable
ADV_OOH <- data$ADV_OOH_Euros
ADV_SocialMedia <- data$ADV_SocialMedia_Euros

## control variables
covid <- data$covid_stringency_index
temp <- data$temp_mean



## lag variables
lag.sales <- Lag(sales)     
lag.aware <- Lag(aware)

# mediator regression
m1 <- lm(aware ~ -1 + lag.aware + ADV_OOH + ADV_SocialMedia + covid + temp)
summary(m1)
```
```{r}
# lag.aware, ooh, social matter

# DV regression
m2 <- lm(sales ~ -1 + lag.sales + aware + ADV_OOH + ADV_SocialMedia + covid + temp)
summary(m2)
```
```{r}
# Steady State Effect = beta / (1 - lambda)

# a-path
a1.est <- m1$coeff[2] / (1 - m1$coeff[1])
a2.est <- m1$coeff[3] / (1 - m1$coeff[1])
# b-path
b.est <- m2$coeff[2] / (1 - m2$coeff[1])
# c-path
c1.est <- m2$coeff[3]  / (1 - m2$coeff[1]) # Direct effet OHH
c2.est <- m2$coeff[4]  / (1 - m2$coeff[1]) # Direct effect SocialMedia

# mediation effects a-path x b-path
a1b.est <- a1.est * b.est
a2b.est <- a2.est * b.est

# Total Effects for each independent variable
tot1.est <- c1.est + a1b.est # This is total effect for OHH
tot2.est <- c2.est + a2b.est # This is total effect for socialmedia
```

```{r}
# create parameter vector and var-covar matrix of relevany coefficients from m1 and m2 models
m1.param <- as.matrix(coef(m1))
m1.vcov <- vcov(m1)

m2.param <- as.matrix(coef(m2))
m2.vcov <- vcov(m2)

# Monte Carlo draws
n.MC <- 1000
draws.m1 <- mvrnorm(n.MC, m1.param, m1.vcov)
draws.m2 <- mvrnorm(n.MC, m2.param, m2.vcov)

# a1-path (OOH to Awareness)
a1.sim <- draws.m1[, "ADV_OOH"] / (1 - draws.m1[, "lag.aware"])

# a2-path (Social to Awareness)
a2.sim <- draws.m1[, "ADV_SocialMedia"] / (1 - draws.m1[, "lag.aware"])

# b-path (Awareness to Sales)
b.sim <- draws.m2[, "aware"] / (1 - draws.m2[, "lag.sales"])

# Mediation effect a1-path x b-path and a2-path x b-path
ab1.sim <- a1.sim * b.sim
ab2.sim <- a2.sim * b.sim

# Total effect = c + a*b for both OOH and Social
c1.sim <- draws.m2[, "ADV_OOH"] / (1 - draws.m2[, "lag.sales"])
tot1.sim <- c1.sim + ab1.sim

c2.sim <- draws.m2[, "ADV_SocialMedia"] / (1 - draws.m2[, "lag.sales"])
tot2.sim <- c2.sim + ab2.sim


# Results: MC Estimates and CIs for both OOH and Social
a1.res <- quantile(a1.sim, probs = c(0.5, 0.025, 0.975))
a2.res <- quantile(a2.sim, probs = c(0.5, 0.025, 0.975))
b.res <- quantile(b.sim, probs = c(0.5, 0.025, 0.975))
ab1.res <- quantile(ab1.sim, probs = c(0.5, 0.025, 0.975))
ab2.res <- quantile(ab2.sim, probs = c(0.5, 0.025, 0.975))
total1.res <- quantile(tot1.sim, probs = c(0.5, 0.025, 0.975), na.rm = TRUE)
total2.res <- quantile(tot2.sim, probs = c(0.5, 0.025, 0.975), na.rm = TRUE)
```

```{r}
out.mediation.res <- rbind(a1.res, a2.res, b.res, ab1.res, ab2.res, total1.res, total2.res)
colnames(out.mediation.res) <- c("Median", "2.5% CIs", "97.5% CIs")
rownames(out.mediation.res) <- c("OOH -> Aware", "Social -> Aware", "Aware -> Sales", "OOH -> Aware -> Sales (Indirect)", "Social -> Aware -> Sales (Indirect)", "OOH Total Effect", "Social Total Effect")

print(round(out.mediation.res, digits = 4))
```

